In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Perceptron
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from tensorflow.keras import Sequential #it lets you build a neural network layer by layer in Keras
from tensorflow.keras.layers import Dense #Dense makes the final prediction
from tensorflow.keras.layers import Convolution2D #it extracts features
from tensorflow.keras.layers import Flatten #it convers all into 1-D
from tensorflow.keras.layers import MaxPooling2D #it reduces the size
from tensorflow.keras.layers import Dropout #Dropout prevents overfitting
from tensorflow.keras.utils import to_categorical #convert numeric class labels into one hot encoded format for training c;assification models

In [ ]:
df = pd.read_csv('train.csv')

In [ ]:
df.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
df.shape

(42000, 785)

In [ ]:
df.columns

Index(['label', 'pixel0', 'pixel1', 'pixel2', 'pixel3', 'pixel4', 'pixel5',
       'pixel6', 'pixel7', 'pixel8',
       ...
       'pixel774', 'pixel775', 'pixel776', 'pixel777', 'pixel778', 'pixel779',
       'pixel780', 'pixel781', 'pixel782', 'pixel783'],
      dtype='object', length=785)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42000 entries, 0 to 41999
Columns: 785 entries, label to pixel783
dtypes: int64(785)
memory usage: 251.5 MB

In [ ]:
df.isnull().sum()

label       0
pixel0      0
pixel1      0
pixel2      0
pixel3      0
           ..
pixel779    0
pixel780    0
pixel781    0
pixel782    0
pixel783    0
Length: 785, dtype: int64

In [ ]:
x = df.drop('label', axis = 1)
y = df['label']

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y)

In [ ]:
x

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
y

0        1
1        0
2        1
3        4
4        0
        ..
41995    0
41996    1
41997    7
41998    6
41999    9
Name: label, Length: 42000, dtype: int64

In [ ]:
x_train

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
33994,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
34262,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22646,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
30780,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8484,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2979,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22620,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12309,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18651,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2335,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
x_test

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
16715,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
684,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
367,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19709,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
40597,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27031,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
412,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23046,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15714,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10510,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
x_train = x_train.astype("float32") / 255.0
x_test = x_test.astype("float32") / 255.0

In [ ]:
x_train_img = x_train.values.reshape(-1, 28, 28)
x_test_img = x_test.values.reshape(-1, 28, 28)

In [ ]:
x_train_img

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]])

In [ ]:
y_train_cat = to_categorical(y_train, 10)
y_test_cat = to_categorical(y_test, 10)

In [ ]:
#perceptron model
perceptron = Sequential([
    Flatten(input_shape = (28,28)),
    Dense(10, activation = "softmax")
])

In [ ]:
perceptron.compile(optimizer= 'sgd', loss = 'categorical_crossentropy', metrics = ["accuracy"])

In [ ]:
history_percp = perceptron.fit(x_train_img, y_train_cat, epochs = 5,
                               batch_size = 32, validation_data = (x_test_img, y_test_cat), verbose = True)

Epoch 1/5
985/985 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7715 - loss: 0.9662 - val_accuracy: 0.8509 - val_loss: 0.6260
Epoch 2/5
985/985 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8664 - loss: 0.5413 - val_accuracy: 0.8699 - val_loss: 0.5030
Epoch 3/5
985/985 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8818 - loss: 0.4616 - val_accuracy: 0.8784 - val_loss: 0.4511
Epoch 4/5
985/985 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8891 - loss: 0.4225 - val_accuracy: 0.8831 - val_loss: 0.4233
Epoch 5/5
985/985 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8940 - loss: 0.3983 - val_accuracy: 0.8864 - val_loss: 0.4038

In [ ]:
acc_percp = perceptron.evaluate(x_test_img, y_test_cat, verbose = 0)[1]

In [ ]:
acc_percp

0.8863809704780579

In [ ]:
#ANN
ann = Sequential([
    Flatten(input_shape = (28,28)),
    Dense(128, activation = "relu"),
    Dense(64, activation = "relu"),
    Dense(10, activation = "softmax")
])

In [ ]:
ann.compile(optimizer= 'adam', loss= 'categorical_crossentropy', metrics = ['accuracy'])

In [ ]:
history_ann = ann.fit(x_train_img, y_train_cat, epochs = 5, batch_size=32, validation_data=(x_test_img, y_test_cat), verbose = True)

Epoch 1/5
985/985 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - accuracy: 0.9086 - loss: 0.3095 - val_accuracy: 0.9450 - val_loss: 0.1782
Epoch 2/5
985/985 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.9593 - loss: 0.1346 - val_accuracy: 0.9515 - val_loss: 0.1513
Epoch 3/5
985/985 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.9710 - loss: 0.0895 - val_accuracy: 0.9632 - val_loss: 0.1206
Epoch 4/5
985/985 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.9785 - loss: 0.0670 - val_accuracy: 0.9649 - val_loss: 0.1131
Epoch 5/5
985/985 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.9850 - loss: 0.0485 - val_accuracy: 0.9719 - val_loss: 0.0947

In [ ]:
acc_ann = ann.evaluate(x_test_img, y_test_cat, verbose = 0)[1]

In [ ]:
acc_ann

0.9719047546386719

In [ ]:
x_train_cnn = x_train.values.reshape(-1,28,28,1) #if we have to use RGB image then chnage 1 to 3
x_test_cnn = x_test.values.reshape(-1,28,28,1)

In [ ]:
#CNN
cnn = Sequential([
    Convolution2D(32, kernel_size=(3,3), activation = "relu", input_shape = (28,28,1)),
    MaxPooling2D(pool_size=(2,2)),
    Convolution2D(64, kernel_size = (3,3),activation= "relu"),
    MaxPooling2D(pool_size=(2,2)),
    Flatten(),
    Dense(128,activation="relu"),
    Dropout(0.5),
    Dense(10, activation="softmax")
])

In [ ]:
cnn.compile(optimizer = 'adam', loss='categorical_crossentropy', metrics = ["accuracy"])

In [ ]:
history_cnn = cnn.fit(x_train_cnn, y_train_cat, epochs = 5, batch_size= 32, validation_data= (x_test_cnn, y_test_cat), verbose = True)

Epoch 1/5
985/985 ━━━━━━━━━━━━━━━━━━━━ 37s 36ms/step - accuracy: 0.9090 - loss: 0.2926 - val_accuracy: 0.9775 - val_loss: 0.0735
Epoch 2/5
985/985 ━━━━━━━━━━━━━━━━━━━━ 32s 33ms/step - accuracy: 0.9679 - loss: 0.1087 - val_accuracy: 0.9789 - val_loss: 0.0678
Epoch 3/5
985/985 ━━━━━━━━━━━━━━━━━━━━ 34s 34ms/step - accuracy: 0.9776 - loss: 0.0763 - val_accuracy: 0.9847 - val_loss: 0.0475
Epoch 4/5
985/985 ━━━━━━━━━━━━━━━━━━━━ 33s 33ms/step - accuracy: 0.9810 - loss: 0.0617 - val_accuracy: 0.9856 - val_loss: 0.0442
Epoch 5/5
985/985 ━━━━━━━━━━━━━━━━━━━━ 48s 40ms/step - accuracy: 0.9843 - loss: 0.0521 - val_accuracy: 0.9887 - val_loss: 0.0377

In [ ]:
acc_cnn = cnn.evaluate(x_test_cnn, y_test_cat, verbose = 0)[1]

In [ ]:
acc_cnn

0.9886666536331177